### ISSUE TITLE
Question for job_id = int(os.environ[args.var_id]) - 1

### ISSUE THREAD

**Issue by Miracle-Yao** [hoffmangroup/umap#22]
Hi, @mehrankr 

I am using the `PBS` system to submit tasks instead of `slurm`, and when I run the `unify_bowtie.py`, the following condition occurs. The command I used is list as follow:

```
for i in {0..19}; do
python /home/software/umap-1.2.1/umap/unify_bowtie.py \
/home/data/umap/GenomeMappability/kmers/k90 \
/home/data/umap/GenomeMappability/chrsize.tsv -job_id $i
done
```
I get error as follow:
```
Traceback (most recent call last):
  File "/home/software/umap-1.2.1/umap/unify_bowtie.py", line 168, in <module>
    job_id = int(os.environ[args.var_id]) - 1
  File "/home/miniconda3/envs/python2/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'SGE_TASK_ID'
```
In fact there are 20 chromosomes in total, in the order chr1, chr10, chr11,..... Only chr1 produces this error, the other chromosomes work fine. That means I was able to generate `uint8.unique.gz` files corresponding to chromosomes besides chr1. I've tested changing `{0..19}` to `{0..20}`, `{1..20}` and found that it never produces `chr1.uint8.unique.gz`. Sometimes it's out of range.

What should I do to solve this problem？
I'm looking forward to hearing from you.

Best regards,
Yao

**Comment by mehrankr** [comment]
Dear Yao,

The particular error message you receive is because of the lack of environmental variable.
e.g. You can try this:
```
for i in {0..19}; do
export SGE_TASK_ID=$i
python /home/software/umap-1.2.1/umap/unify_bowtie.py \
/home/data/umap/GenomeMappability/kmers/k90 \
/home/data/umap/GenomeMappability/chrsize.tsv -job_id $i
done
``` 
And you wouldn't get that error.
The script was optimized for SGE and it has a manual `-1` step to map 1-based indexing to 0-based indexing. If that's causing problems, you can modify the scripts to not subtract `1` from the job ID.

Hope this is an immediate solution while Eric prepares a new release without this particular incompatibility issue.

Best,
Mehran
