### ISSUE TITLE
Umap repository missing from bitbucket server

### ISSUE THREAD

**Issue by Jonbroad15** [hoffmangroup/umap#3]
I am attempting to install Umap however I believe the repository is moved away from the bitbucket server.

Upon trying: 
`hg clone https://bitbucket.org/hoffmanlab/umap`

I receive a `404: Not Found` error. Can you please link me to the new location of the files?

**Comment by EricR86** [comment]
@Jonbroad15 The repository is [right here on Github](https://github.com/hoffmangroup/umap). You can use `git clone https://github.com/hoffmangroup/umap.git`.

We want to remove all links to the bitbucket repository since we had to migrate away. Thank you for pointing out that the documentation needs to be updated!
